### PR TITLE
Async refactoring as in Exercise from 18.May.2018

### PR DESCRIPTION
**Pull request by AndreyKodzhabashev**
I`ve also copied in my repo the must corrections, made from SonnyRR-Vasil Kotsev (Thanks, mate)

### CODE REVIEW

**Comment by SonnyRR** [comment]
There is no point in copying fixes in files/code between pull requests as it would result in a merge if both were to be approved.

**Comment by AndreyKodzhabashev** [comment]
Agree, but wanted to continue working with the code. And it couldn't be done with my version. And as Ivo didn't approved yet your fixes - i didn't had a choice. As far as I know, of course.
And as my "corrections" are exact copy of yours, I decided it will not cause a merge conflict (if causes - Ivo will be able to take an easy decision).
 Excuse me. It is no disrespect for you.

**Comment by SonnyRR** [comment]
My point is that every pull request needs to be merged into the master branch if approved by member/s of this repo either way, so it will override them. It's just unnecessary code repetition that is duplicate between pull requests. There is already a duplicate request (people don't read...) https://github.com/SoftUni/csharp-web/pull/6# for the same fix, making it 3 waiting for approval, fixes of the same thing. It would be better if these requests were reviewed faster, because the build is failing, but its weekend days so... After all, Ivo will review them and cherry-pick the commits probably on the first working day of the week, so we will need to wait until tomorrow probably.

**Comment by AndreyKodzhabashev** [comment]
Hi, Vasil, yesterday i realized the idiotic bug i created in HttpRequest class. Still cannot believe it... Anyhow.  Is there any particular reason you fixed the bug with an explicit casting or it is just your personal preference. 
In the current version in my fork i have remastered it by changing the interface and as a consequence, the necessary changes in the implementation class.
Do you have any remarks?

**Comment by SonnyRR** [comment]
We use IDictionary<TKey,TVal> for fast searching using its hashtable. We use "object" as a generic type parameter in order to use "boxing and unboxing". When we have multiple kvp's send through a form such as checkboxes with the same key, we can use a linear data structure like a HashSet as most real frameworks do - they parse them to a collection. As it is it will be hard to manage pairs that have one value member as we will have to create new memory for each set and only have one member in it. But most importantly this is a requirement set by the course team, so there should be some kind of a discussion on this and how we procedure from now on.

**Pull request merged**
